server {
    # Lắng nghe giao thức HTTP và tự động chuyển hướng sang HTTPS
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    # Lắng nghe giao thức HTTPS
    listen 443 ssl;
    server_name localhostl;

    # Đường dẫn tới chứng chỉ SSL chúng ta vừa tạo
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    # 1. Điều hướng request của giao diện về Vite (web_app)
    location / {
        proxy_pass http://web_app:5173; # Trỏ thẳng vào cổng mặc định của Vite trong container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Cấu hình bắt buộc để Vite HMR (Hot Reload) hoạt động qua Proxy
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 2. Phục vụ file ảnh trong thư mục uplodas
    location /uploads/{
        # Ánh xạ URL /uploads/ vào thư mục /app/uploads/ bên trong container Nginx
        alias /app/uploads/;
        # Cấp quyền truy cập
        autoindex off;
    }

    # 3. Điều hướng request API về Backend (api_server)
    location /api/ {
        proxy_pass http://api_server:8000/api/; # Trỏ thẳng vào cổng của api_server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
